# Generated by Django 2.0 on 2019-06-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dublin_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Locations',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='stop_id')),
                ('stop_name', models.CharField(max_length=50, verbose_name='stop_name')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=15, verbose_name='longitude')),
            ],
        ),
    ]
