# Generated by Django 2.0 on 2019-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dublin_map', '0002_bus_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_locations',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='bus_locations',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='longitude'),
        ),
    ]
